# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps/x86_64/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps/x86_64


PRODUCT_PACKAGES += \
    libjni_latinimegoogle \
    GmsCore \
    Phonesky

ifeq ($(TARGET_IS_GROUPER),)

PRODUCT_PACKAGES += \
    Velvet \
    SetupWizard
endif

$(call inherit-product, vendor/gapps/common/common-vendor.mk)
