# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps/common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter arm arm64 x86,$(TARGET_ARCH)),)

endif
