# Copyright (C) 2017-2022 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/gapps//setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps/

PRODUCT_COPY_FILES += \
    vendor/gapps/common/proprietary/etc/permissions/com.google.android.dialer.support.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.google.android.dialer.support.xml \
    vendor/gapps/common/proprietary/etc/permissions/com.google.android.maps.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.google.android.maps.xml \
    vendor/gapps/common/proprietary/etc/permissions/privapp-permissions-google-p.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-google-p.xml \
    vendor/gapps/common/proprietary/etc/permissions/privapp-permissions-google-ps.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-google-ps.xml \
    vendor/gapps/common/proprietary/etc/permissions/privapp-permissions-google.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-google.xml \
    vendor/gapps/common/proprietary/etc/sysconfig/google-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/google-hiddenapi-package-whitelist.xml \
    vendor/gapps/common/proprietary/etc/sysconfig/google.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/google.xml \
    vendor/gapps/common/proprietary/etc/sysconfig/google_build.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/google_build.xml

PRODUCT_PACKAGES += \
    GoogleCalendarSyncAdapter \
    GoogleContactsSyncAdapter \
    PrebuiltExchange3Google \
    GoogleFeedback \
    GooglePartnerSetup \
    GoogleServicesFramework \
    Phonesky \
    com.google.android.dialer.support \
    com.google.android.maps
ifeq ($(TARGET_IS_GROUPER),)

PRODUCT_PACKAGES += \
    AndroidMigratePrebuilt \
    SetupWizardPrebuilt
endif
