# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps/arm/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps/arm

PRODUCT_COPY_FILES += \
    vendor/gapps/arm/proprietary/product/lib/libjni_latinimegoogle.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libjni_latinimegoogle.so

PRODUCT_PACKAGES += \
    PrebuiltGmsCore

ifeq ($(TARGET_IS_GROUPER),)
PRODUCT_COPY_FILES += \
    vendor/gapps/arm/proprietary/product/app/MarkupGoogle/lib/arm/libsketchology_native.so:$(TARGET_COPY_OUT_PRODUCT)/app/MarkupGoogle/lib/arm/libsketchology_native.so

PRODUCT_PACKAGES += \
    GoogleTTS \
    MarkupGoogle \
    talkback \
    SetupWizardPrebuilt \
    Velvet
endif

$(call inherit-product, vendor/gapps/common/common-vendor.mk)
