# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps/x86/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps/x86

PRODUCT_COPY_FILES += \
    vendor/gapps/x86/proprietary/product/lib/libjni_latinimegoogle.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libjni_latinimegoogle.so

PRODUCT_PACKAGES += \
    GmsCore \
    Phonesky

ifeq ($(TARGET_IS_GROUPER),)

PRODUCT_PACKAGES += \
    Velvet \
    SetupWizard
endif

$(call inherit-product, vendor/gapps/common/common-vendor.mk)
